# This is a basic workflow to help you get started with Actions

name: GithubActions-02

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
        branch:
          required: true
          type: string
          description: Enter the dev branch to deploye on Automation Env

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Check if branch exists
        id: check_branch
        run: |
          BRANCH="${{ github.event.inputs.branch }}"
          echo "Checking for branch: $BRANCH"
          
          if git ls-remote --heads origin "$BRANCH" | grep -q "$BRANCH"; then
            echo "Branch exists"
          else
            echo "❌ Branch '$BRANCH' not found on remote."
            echo "Cancelling workflow."
            exit 1
          fi

      # Runs a single command using the runners shell
      - name: Trigger TestGithubActions Pipeline
        run: |
          echo Triggering pipeline for testGitHubActions repo,
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            https://api.github.com/repos/khizarsheikh/testGitHubActions/actions/workflows/main.yml/dispatches \
            -d '{"ref":"main"}'
