name: pre-commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Run eslint
        run: echo running eslint

      - name: Run prettier
        run: echo running prettier:write
